/**
 * File Name: DiscountCategoryNames_PP
 *
 * @author: architect ir. Wilhelmus G.J. Velzeboer
 */
public with sharing class DiscountCategoryNames_PP {
  public static final String SUPPORT = 'Support';
  public static final String SERVICES = 'Services';
  public static final String THIRD_PARTY = '3rd Party';
  public static final String PRODUCT = 'Product';
  public static final String RESTRICTED = 'Restricted';
}