@IsTest(isParallel=true)
public class LeadDoNotContactTest {
    // TODO: refactor batch
    // @isTest
    // public static void Test1(){
        
    //     // Data setup
    //     Lead l = new Lead();
    //     l.LastName = 'Test273642';
    //     l.Company = 'Test293732';
    //     l.Do_Not_Contact__c = Date.today();
    //     l.Status = 'Suspect';
    //     l.Country = 'United States';
    //     l.Email = 'joe.test@test.com';
    //     insert l;
        
    //     // Run the code
    //     Test.startTest();
    //     (new LeadDoNotContactBatch()).execute(null);
    //     Test.stopTest();
        
    //     // Verify Results
    //     l = [SELECT Status FROM Lead WHERE Id = :l.Id];
    //     System.assertEquals('New', l.Status);
    // }
}