@isTest(SeeAllData=true)
public class RHX_TEST_pse_Budget {
  /*  static testMethod void RHX_Testmethod() {
        List<sObject> sourceList = [SELECT Id 
            FROM pse__Budget__c ORDER BY LastModifiedDate DESC LIMIT 1];
        if(sourceList.size() == 0) {
            sourceList.add(
                    new pse__Budget__c()
            );
        }
        rh2.ParentUtil.UpsertRollupTestRecords( sourceList );
    } */
}